---

- name:  Allow firewalld ports
  ansible.posix.firewalld:
    port: "{{ item }}" 
    permanent: true
    state: enabled
  with_items: "{{ firewall_list }}"      

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded