---

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ item }}" 
    owner: "{{os_user}}"
    group: "{{os_user}}"
    mode: "{{ file_mode }}" 
    recurse: "{{ recursive }}" 
  with_items: "{{ file_list }}"        