---

- include_tasks: update.yml
  when: update|default(False)==True  
          
- include_tasks: download_bin.yml
  when: download_bin|default(False)==True

- include_tasks: adduser.yml
  when: adduser|default(False)==True

- include_tasks: allowport.yml
  when: allowport|default(False)==True

- include_tasks: deletelogs.yml
  when: deletelogs|default(False)==True     

- include_tasks: create_log.yml
  when: create_log|default(False)==True  
  
- include_tasks: mail.yml
  when: mail|default(False)==True
          