---

- include_tasks: update.yml
  when: update|default(False)==True  
          
- include_tasks: download_bin.yml
  when: download_bin|default(False)==True

- include_tasks: adduser.yml
  when: adduser|default(False)==True

- include_tasks: allowport.yml
  when: allowport|default(False)==True

- include_tasks: deletelogs.yml
  when: deletelogs|default(False)==True     

- include_tasks: create_log.yml
  when: create_log|default(False)==True  
  
- include_tasks: mail.yml
  when: mail|default(False)==True

- include_tasks: setup_bashrc.yml
  when: setup_bashrc|default(False)==True   
          
- include_tasks: download_package.yml
  when: download_package|default(False)==True            

- include_tasks: security_limits.yml
  when: security_limits|default(False)==True    
  
- include_tasks: unarchive.yml
  when: unarchive|default(False)==True    

- include_tasks: fail_if_exist.yml
  when: fail_if_exist|default(False)==True    

- include_tasks: cleanup.yml
  when: cleanup|default(False)==True    
  
- include_tasks: get_raw_disk.yml
  when: get_raw_disk|default(False)==True  

- include_tasks: create_partition.yml
  when: create_partition|default(False)==True and inventory_hostname.split(".")[0] | lower == server.split(".")[0] | lower 

- include_tasks: create_partition_nolog.yml
  when: create_partition_nolog|default(False)==True and inventory_hostname.split(".")[0] | lower == server.split(".")[0] | lower 
    
- include_tasks: remove_partition_nolog.yml
  when: remove_partition_nolog|default(False)==True and inventory_hostname.split(".")[0] | lower == server.split(".")[0] | lower 
                