---

- name: Create folder if not exist
  ansible.builtin.file:
    path: "{{app.folder}}"
    state: directory

- name: unarchive tar
  ansible.builtin.unarchive:
    src: "{{archive_file}}"
    dest: "{{app.folder}}"
    remote_src: yes
    